# Generated by Django 3.1.6 on 2021-12-04 08:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="services",
        ),
        migrations.AddField(
            model_name="clinic",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="image1",
            field=models.ImageField(blank=True, upload_to="image/clinic"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="image2",
            field=models.ImageField(blank=True, upload_to="image/clinic"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="image3",
            field=models.ImageField(blank=True, upload_to="image/clinic"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="phone_number",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="Phone_number",
        ),
    ]
