# Generated by Django 3.1.6 on 2021-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_auto_20211212_0700"),
        ("clinic", "0006_clinic_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="location",
        ),
        migrations.AddField(
            model_name="clinic",
            name="location",
            field=models.ManyToManyField(to="location.Location"),
        ),
    ]
