# Generated by Django 3.1.6 on 2021-12-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partial", "0004_auto_20211215_0613"),
        ("clinic", "0008_auto_20211212_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="company",
            field=models.ManyToManyField(related_name="clinic", to="partial.Company"),
        ),
    ]
