# Generated by Django 3.1.6 on 2021-12-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_city_province_zone"),
        ("clinic", "0011_auto_20211222_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="location.zone"
            ),
        ),
    ]
