# Generated by Django 3.1.6 on 2021-12-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="level",
        ),
        migrations.RemoveField(
            model_name="location",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="location",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="location",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="location",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="location",
            name="tree_id",
        ),
    ]
