# Generated by Django 3.1.6 on 2021-12-25 08:03

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0012_auto_20211225_0803"),
        ("location", "0003_city_province_zone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="zone",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="location.city",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="location.province",
            ),
        ),
    ]
