# Generated by Django 3.1.6 on 2021-12-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20211225_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='parent',
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location.province'),
        ),
    ]
