# Generated by Django 3.1.6 on 2022-01-11 11:39

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(default='', max_length=125)),
                ('family', models.CharField(default='', max_length=125)),
                ('is_done', models.BooleanField(default=False)),
                ('is_clinic', models.BooleanField(default=False)),
                ('referral_code', models.CharField(default=account.models.UniqueGenerator, max_length=8)),
                ('invite_code', models.CharField(default='', max_length=8)),
                ('clinic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
