# Generated by Django 3.1.6 on 2021-11-12 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("expire", models.DateTimeField()),
                ("phone_number", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photo_History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="images/photo_history")),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("national_code", models.IntegerField(blank=True, unique=True)),
                ("phone_number", models.CharField(max_length=11)),
                ("birthday", models.DateField(blank=True)),
                ("name", models.CharField(blank=True, max_length=125)),
                ("family", models.CharField(blank=True, max_length=125)),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="images/profile/"),
                ),
                (
                    "insurance_scan",
                    models.ImageField(blank=True, upload_to="images/insurance_scab/"),
                ),
                (
                    "insurance_code",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="insurance  must be entered in the format: '12345678'. 8 digits allowed.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("invite_code", models.CharField(blank=True, max_length=10, null=True)),
                ("is_doctor", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
