# Generated by Django 3.1.6 on 2021-11-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20211112_2042"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="expire",
        ),
    ]
