# Generated by Django 3.1.6 on 2022-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_clinic',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('عادی', 'عادی'), ('کلینیک', 'کلینیک'), ('فروشگاه', 'فروشگاه')], default='asd', max_length=10),
            preserve_default=False,
        ),
    ]
