# Generated by Django 3.1.6 on 2021-11-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_code_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="number",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="code",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
