# Generated by Django 3.1.6 on 2021-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_auto_20211113_0653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
    ]
