# Generated by Django 3.1.6 on 2021-11-15 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0005_auto_20211113_1108"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_code",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=125, null=True)),
                ("family", models.CharField(blank=True, max_length=125, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile/"
                    ),
                ),
                (
                    "insurance_scan",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/insurance_scab/"
                    ),
                ),
                (
                    "insurance_code",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="insurance  must be entered in the format: '12345678'. 8 digits allowed.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("invite_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Photo_History",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
