# Generated by Django 3.1.6 on 2021-11-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_auto_20211115_0620"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="insurance_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="insurance_scan",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
    ]
