# Generated by Django 3.1.6 on 2021-12-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_clinic_company"),
        ("account", "0009_profile_is_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="clinic",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_clinic",
            field=models.BooleanField(default=False),
        ),
    ]
