# Generated by Django 3.1.6 on 2022-01-10 05:51

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=account.models.UniqueGenerator, max_length=8),
        ),
    ]
