# Generated by Django 3.1.6 on 2022-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220109_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.IntegerField(blank=True, default=213, unique=True),
            preserve_default=False,
        ),
    ]
