# Generated by Django 3.1.6 on 2021-11-30 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Common_Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images/common_course")),
                ("description", ckeditor.fields.RichTextField()),
                ("source", models.CharField(max_length=125)),
                ("video", models.FileField(upload_to="common_course/video")),
            ],
        ),
    ]
