# Generated by Django 3.1.6 on 2021-12-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commoncourse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="common_course",
            name="description",
            field=models.TextField(),
        ),
    ]
