# Generated by Django 3.1.6 on 2021-12-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commoncourse", "0002_auto_20211209_0822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="common_course",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="common_course/video"
            ),
        ),
    ]
