# Generated by Django 3.1.6 on 2022-01-11 11:39

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="عنوان برچسب"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "برچسب ها",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="IpAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آی پی آدرس")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
            ],
            options={
                "verbose_name": "آی پی آدرس",
                "verbose_name_plural": "آی پی آدرس ها",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان مقاله")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان در url"
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="محتوا")),
                (
                    "image",
                    models.ImageField(
                        upload_to="image/blog", verbose_name="تصویر مقاله"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="وضعیت انتشار"),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to="is_superuser",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "hits",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="blog.IpAddress",
                        verbose_name="بازید",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blogs",
                        to="blog.BlogTag",
                        verbose_name="تگ ها / برچسب ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-publish_time"],
            },
        ),
    ]
