# Generated by Django 3.1.6 on 2022-01-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='clinic',
            field=models.CharField(max_length=125),
        ),
    ]
