# Generated by Django 3.1.6 on 2021-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_auto_20211205_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="From",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="To",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="message",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
