# Generated by Django 3.1.6 on 2021-12-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_auto_20211212_0700"),
        ("clinic", "0007_auto_20211212_1117"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="location",
        ),
        migrations.AddField(
            model_name="clinic",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.location",
            ),
            preserve_default=False,
        ),
    ]
