# Generated by Django 3.1.6 on 2021-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_clinic_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_clinic',
            field=models.BooleanField(default=False),
        ),
    ]
