# Generated by Django 3.1.6 on 2021-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0012_auto_20211225_0803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="description",
            field=models.TextField(),
        ),
    ]
