# Generated by Django 3.1.6 on 2021-12-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0014_auto_20211228_0338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("کلینیک", "کلینیک"),
                    ("مطب", "مطب"),
                    ("لابراتوار", "لابراتوار"),
                    ("رادیوگرافی", "رادیوگرافی"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
