# Generated by Django 3.1.6 on 2021-12-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0015_auto_20211229_0256"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="image4",
            field=models.ImageField(blank=True, upload_to="image/clinic"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="image5",
            field=models.ImageField(blank=True, upload_to="image/clinic"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
