# Generated by Django 3.1.6 on 2021-12-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0016_auto_20211229_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="contracted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinic",
            name="parvaneh_clinic",
            field=models.ImageField(blank=True, null=True, upload_to="images/clinic/"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="parvaneh_masole",
            field=models.ImageField(blank=True, null=True, upload_to="images/clinic/"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="telegram",
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="whats_up",
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="logo",
            field=models.ImageField(upload_to="image/clinic"),
        ),
    ]
