# Generated by Django 3.1.6 on 2022-01-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20211229_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='image5',
        ),
    ]
