# Generated by Django 3.1.6 on 2022-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
