# Generated by Django 3.1.6 on 2022-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_winner_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
