# Generated by Django 3.1.6 on 2021-11-12 20:38

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About_Us",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact_Us",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "Phone_Number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '9137866088'. 10 digits allowed.",
                                regex="^\\d{10}$",
                            )
                        ],
                        verbose_name="شماره تلفن",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="پیام")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "icon",
                    models.ImageField(upload_to="images/icon/", verbose_name="آیکون"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
                (
                    "picture",
                    models.ImageField(
                        upload_to="images/sliders/%Y/%m", verbose_name="تصویر"
                    ),
                ),
            ],
        ),
    ]
