# Generated by Django 3.1.6 on 2021-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="title",
        ),
        migrations.AddField(
            model_name="slider",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
