# Generated by Django 3.1.6 on 2021-11-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_auto_20211124_0850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact_us",
            name="created",
        ),
        migrations.RemoveField(
            model_name="contact_us",
            name="message",
        ),
        migrations.RemoveField(
            model_name="contact_us",
            name="name",
        ),
        migrations.RemoveField(
            model_name="contact_us",
            name="title",
        ),
        migrations.AddField(
            model_name="about_us",
            name="image",
            field=models.ImageField(default=1, upload_to="images/about_us/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact_us",
            name="time",
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
