# Generated by Django 3.1.6 on 2021-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_auto_20211124_0855"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about_us",
            old_name="Content",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="about_us",
            name="image",
        ),
        migrations.RemoveField(
            model_name="contact_us",
            name="Phone_Number",
        ),
        migrations.RemoveField(
            model_name="contact_us",
            name="time",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="url",
        ),
        migrations.AddField(
            model_name="contact_us",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact_us",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="title",
            field=models.CharField(default="dsasdfsd", max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="icon",
            field=models.ImageField(upload_to="images/icon/"),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="title",
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name="slider",
            name="picture",
            field=models.ImageField(upload_to="images/sliders/%Y/%m"),
        ),
    ]
