# Generated by Django 3.1.6 on 2022-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20211129_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=models.TextField(),
        ),
    ]
