# Generated by Django 3.1.6 on 2022-01-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                (
                    "icon",
                    models.ImageField(blank=True, upload_to="image/category/icon/"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub",
                        to="shop.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sell",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("discount_percent", models.IntegerField()),
                ("image", models.ImageField(upload_to="images/produce/")),
                ("image2", models.ImageField(blank=True, upload_to="images/produce/")),
                ("image3", models.ImageField(blank=True, upload_to="images/produce/")),
                ("image4", models.ImageField(blank=True, upload_to="images/produce/")),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("phone_number", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=500)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produce",
                        to="shop.category",
                    ),
                ),
            ],
        ),
    ]
