# Generated by Django 3.1.6 on 2021-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, upload_to="images/produce/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, upload_to="images/produce/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image4",
            field=models.ImageField(blank=True, upload_to="images/produce/"),
        ),
    ]
