# Generated by Django 3.1.6 on 2021-12-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20211212_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, upload_to="image/category/icon/"),
        ),
    ]
