# Generated by Django 3.1.6 on 2022-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
