# Generated by Django 3.1.6 on 2022-01-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_is_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_send',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=111, max_digits=10),
            preserve_default=False,
        ),
    ]
