# Generated by Django 3.1.6 on 2022-01-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220104_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
