# Generated by Django 3.1.6 on 2022-01-11 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11)),
                ('ID_photo', models.ImageField(upload_to='images/doctor/ID_photo/')),
                ('profile', models.ImageField(upload_to='images/doctor/profile/')),
                ('medical_code', models.CharField(max_length=11)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', doctor.models.IntegerRangeField()),
                ('star', models.PositiveIntegerField(blank=True, null=True)),
                ('parvaneh_tebabat', models.ImageField(blank=True, null=True, upload_to='images/doctor/')),
                ('verified', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='clinic.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('image', models.ImageField(blank=True, upload_to='images/Expertise/')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('image', models.ImageField(upload_to='image/insurance')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=10, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('finish_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time2', models.DateTimeField(default=datetime.datetime.now)),
                ('finish_time2', models.DateTimeField(default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.visittime')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.ManyToManyField(related_name='doctor', to='doctor.Expertise'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.ManyToManyField(to='doctor.Insurance'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', doctor.models.IntegerRangeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='clinic.clinic')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.expertise')),
            ],
        ),
    ]
