# Generated by Django 3.1.6 on 2021-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_doctor_star"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("image", models.ImageField(upload_to="image/insurance")),
            ],
        ),
    ]
