# Generated by Django 3.1.6 on 2021-11-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="insurance",
            field=models.ManyToManyField(to="doctor.Insurance"),
        ),
    ]
