# Generated by Django 3.1.6 on 2021-11-27 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_doctor_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="visittime",
            name="finish_time2",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="visittime",
            name="start_time2",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name="visittime",
            name="doctor",
        ),
        migrations.AddField(
            model_name="visittime",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="finish_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="is_reserved",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
