# Generated by Django 3.1.6 on 2022-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('doctor', '0004_auto_20220122_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ManyToManyField(related_name='doctor', to='clinic.Clinic'),
        ),
    ]
