# Generated by Django 3.1.6 on 2021-11-28 06:07

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_auto_20211127_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="date",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
