# Generated by Django 3.1.6 on 2022-01-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20220122_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='insurance',
        ),
    ]
