# Generated by Django 3.1.6 on 2022-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('doctor', '0006_auto_20220122_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='ID_photo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ManyToManyField(related_name='doctor', to='clinic.Clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.ManyToManyField(related_name='doctor', to='doctor.Expertise'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.ManyToManyField(to='doctor.Insurance'),
        ),
    ]
