# Generated by Django 3.1.6 on 2021-11-29 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_auto_20211128_0607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="finish_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="finish_time2",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time2",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
