# Generated by Django 3.1.6 on 2022-01-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20220122_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='parvaneh_tebabat',
        ),
    ]
