# Generated by Django 3.1.6 on 2021-11-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_auto_20211129_1029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visittime",
            name="is_reserved",
        ),
    ]
