# Generated by Django 3.1.6 on 2021-11-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_remove_visittime_is_reserved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="date",
            field=models.DateField(),
        ),
    ]
