# Generated by Django 3.1.6 on 2022-01-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctor_parvaneh_tebabat'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ID_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor/ID_photo/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='parvaneh_tebabat',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor/profile/'),
        ),
    ]
