# Generated by Django 3.1.6 on 2022-01-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20220123_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ID_photo',
            field=models.FileField(blank=True, null=True, upload_to='images/doctor/ID_photo/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='parvaneh_tebabat',
            field=models.FileField(blank=True, null=True, upload_to='images/doctor/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='images/doctor/profile/'),
        ),
    ]
