# Generated by Django 3.1.6 on 2021-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_auto_20211129_1229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="full_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="medical_code",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="national_code",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
    ]
