# Generated by Django 3.1.6 on 2021-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0010_auto_20211201_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="visittime",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("شنبه", "شنبه"),
                    ("یکشنبه", "یکشنبه"),
                    ("دوشنبه", "دوشنبه"),
                    ("سه شنبه", "سه شنبه"),
                    ("چهارشنبه", "چهارشنبه"),
                    ("پنجشنبه", "پنجشنبه"),
                    ("جمعه", "جمعه"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
