# Generated by Django 3.1.6 on 2022-01-23 12:56

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20220123_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ID_photo',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='parvaneh_tebabat',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True),
        ),
    ]
