# Generated by Django 3.1.6 on 2021-12-07 11:53

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0011_visittime_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="date",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
