# Generated by Django 3.1.6 on 2021-12-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_auto_20211207_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="finish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="finish_time2",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time2",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
