# Generated by Django 3.1.6 on 2021-12-16 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0013_auto_20211207_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="finish_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="finish_time2",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time2",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
