# Generated by Django 3.1.6 on 2021-12-16 06:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_auto_20211216_0619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visittime",
            name="finish_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="finish_time2",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="visittime",
            name="start_time2",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
