# Generated by Django 3.1.6 on 2021-12-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0018_doctordate"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="parvaneh_tebabat",
            field=models.ImageField(blank=True, null=True, upload_to="images/doctor/"),
        ),
    ]
