# Generated by Django 3.1.6 on 2021-12-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0019_doctor_parvaneh_tebabat"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
