# Generated by Django 3.1.6 on 2022-01-08 11:30

from django.db import migrations
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_auto_20220108_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=doctor.models.IntegerRangeField(),
        ),
    ]
