# Generated by Django 3.1.6 on 2021-11-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, null=True)),
                ("family", models.CharField(max_length=125, null=True)),
                ("phone_number", models.CharField(max_length=11, null=True)),
                ("national_code", models.CharField(max_length=125, null=True)),
                ("day", models.CharField(max_length=125, null=True)),
                ("time", models.CharField(max_length=125, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ali",
                        to="doctor.doctor",
                    ),
                ),
            ],
        ),
    ]
