# Generated by Django 3.1.6 on 2021-12-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_auto_20211223_0706'),
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='doctor.doctor'),
        ),
    ]
