# Generated by Django 3.1.6 on 2021-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptions",
            name="description",
            field=models.TextField(),
        ),
    ]
