# Generated by Django 3.1.6 on 2021-12-15 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partial", "0003_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
