# Generated by Django 3.1.6 on 2021-12-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partial", "0004_auto_20211215_0613"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDictionary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("meaning", models.TextField()),
            ],
        ),
    ]
