# Generated by Django 3.1.6 on 2021-12-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partial", "0005_doctordictionary"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDictionaryCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name="doctordictionary",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor/images/dictonary/"
            ),
        ),
        migrations.CreateModel(
            name="ImageOfDict",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "dict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dict",
                        to="partial.doctordictionary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctordictionary",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dict",
                to="partial.doctordictionarycategory",
            ),
        ),
    ]
