# Generated by Django 3.1.6 on 2022-01-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partial', '0007_auto_20211227_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='clinic',
            field=models.CharField(default='sdfgsdfg', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='doctor',
            field=models.CharField(default='sdfgsdf', max_length=125),
            preserve_default=False,
        ),
    ]
